import { Poppins } from 'next/font/google'
import { AppProvider } from './data/context/AppContext'
import './globals.css'
const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin-ext']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <AppProvider>
      <html lang="en">
        <body className={`${poppins.className}`}>{children}</body>
      </html>
    </AppProvider>
  )
}
